/* ============================================================
   STORY SEQUENCER — 36 Scripture Stories Across 6 Volumes
   Each story has 4 to 5 chronological events with kid-friendly
   narratives, scripture references, and thematic artwork motifs.
   Complies with Constitution Article 1 (no depictions of Jesus).
   ============================================================ */
import { shuffle } from "../../utils/random.js";

export const VOLUMES = [
  {
    id: 1,
    title: "Foundations & Patriarchs",
    subtitle: "Creation, the flood, and the fathers of faith",
    icon: "🌱",
    color: "#e88b6a",
    storyIds: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 2,
    title: "Deliverance & Promised Land",
    subtitle: "From Egyptian slavery to the walls of Jericho",
    icon: "🌊",
    color: "#5c8a3a",
    storyIds: [7, 8, 9, 10, 11, 12],
  },
  {
    id: 3,
    title: "Judges, Kings & Prophets",
    subtitle: "Brave leaders, faithful heroes, and fiery prophets",
    icon: "🦁",
    color: "#b08d57",
    storyIds: [13, 14, 15, 16, 17, 18],
  },
  {
    id: 4,
    title: "Faith in Exile & Return",
    subtitle: "Courage in strange lands and rebuilding Jerusalem",
    icon: "👑",
    color: "#3a86ff",
    storyIds: [19, 23, 22, 21, 20, 24],
  },
  {
    id: 5,
    title: "The Life & Teachings of Jesus",
    subtitle: "Good news, wonders on Galilee, and parables of grace",
    icon: "⭐",
    color: "#d94f30",
    storyIds: [25, 26, 27, 28, 29, 30],
  },
  {
    id: 6,
    title: "Resurrection & Early Church",
    subtitle: "The empty tomb, Pentecost fire, and the Gospel spread",
    icon: "🕊️",
    color: "#8a6bbf",
    storyIds: [31, 32, 33, 34, 35, 36],
  },
];

export const STORIES = [
  // --- VOLUME 1: FOUNDATIONS & PATRIARCHS ---
  {
    id: 1,
    volId: 1,
    title: "The Days of Creation",
    subtitle: "God speaks light, sky, seas, creatures, and rest into being",
    scripture: "Genesis 1:1–2:3",
    icon: "🌍",
    color: "#5c8a3a",
    character: "moses",
    art: "creation",
    events: [
      { step: 1, title: "Light in Darkness", text: "God speaks into the darkness and says, 'Let there be light!' and separates light from darkness.", ref: "Genesis 1:3–5" },
      { step: 2, title: "Sky, Seas & Dry Land", text: "God creates the expanse of the sky, gathers the waters into seas, and brings forth plants and trees.", ref: "Genesis 1:6–13" },
      { step: 3, title: "Sun, Moon & Stars", text: "God places the sun, moon, and countless shining stars in the heavens to give light to the earth.", ref: "Genesis 1:14–19" },
      { step: 4, title: "Sea Creatures & Birds", text: "The oceans fill with swimming fish and sea creatures, and birds fly across the open sky.", ref: "Genesis 1:20–23" },
      { step: 5, title: "Animals, Mankind & Rest", text: "God makes land animals, creates mankind in His own image, and rests on the seventh day.", ref: "Genesis 1:24–2:3" },
    ],
  },
  {
    id: 2,
    volId: 1,
    title: "The Garden of Eden",
    subtitle: "A lush paradise home and the promise of hope",
    scripture: "Genesis 2:8–3:24",
    icon: "🌳",
    color: "#2a9d8f",
    character: "moses",
    art: "fruit_vine",
    events: [
      { step: 1, title: "The Garden Home", text: "God plants a lush, beautiful garden in Eden with sweet fruit trees and fresh rivers.", ref: "Genesis 2:8–10" },
      { step: 2, title: "Naming the Animals", text: "Adam cares for the garden and names all the living animals and birds.", ref: "Genesis 2:15, 19–20" },
      { step: 3, title: "Eve Is Created", text: "God creates Eve to be Adam's loving companion, helper, and partner.", ref: "Genesis 2:21–23" },
      { step: 4, title: "The Forbidden Fruit", text: "The serpent tempts Eve, and she and Adam both eat fruit from the tree God told them not to touch.", ref: "Genesis 3:1–6" },
      { step: 5, title: "The First Promise of Hope", text: "God gives the first promise that goodness will overcome evil, and He clothes Adam and Eve.", ref: "Genesis 3:15–21" },
    ],
  },
  {
    id: 3,
    volId: 1,
    title: "Noah's Ark & The Flood",
    subtitle: "Building the big ark and God's rainbow covenant",
    scripture: "Genesis 6–9",
    icon: "🕊️",
    color: "#3e7cb1",
    character: "noah",
    art: "rainbow",
    events: [
      { step: 1, title: "Building the Ark", text: "God tells faithful Noah to build a giant wooden ark with rooms and a roof.", ref: "Genesis 6:13–16" },
      { step: 2, title: "Animals Board Two by Two", text: "Noah's family and pairs of every kind of bird and animal enter the safe ark.", ref: "Genesis 7:7–9" },
      { step: 3, title: "Rain Floods the Earth", text: "Rain pours from the heavens for forty days and nights, lifting the ark above the mountains.", ref: "Genesis 7:17–19" },
      { step: 4, title: "The Dove & Olive Branch", text: "Noah sends out a dove, and it returns carrying a fresh green olive leaf in its beak.", ref: "Genesis 8:10–11" },
      { step: 5, title: "The Rainbow Promise", text: "Everyone steps onto dry land, and God sets a colorful rainbow in the sky as His covenant.", ref: "Genesis 9:12–15" },
    ],
  },
  {
    id: 4,
    volId: 1,
    title: "The Tower of Babel",
    subtitle: "Prideful bricks and the scattering of languages",
    scripture: "Genesis 11:1–9",
    icon: "🏗️",
    color: "#b08d57",
    character: "noah",
    art: "wisdom_scroll",
    events: [
      { step: 1, title: "One Common Language", text: "All people on the earth speak a single language and travel east to settle in a plain.", ref: "Genesis 11:1–2" },
      { step: 2, title: "Baking Strong Bricks", text: "The builders make bricks and mortar, saying, 'Let us build a city and a tower reaching to the sky, and make a great name for ourselves!'", ref: "Genesis 11:3–4" },
      { step: 3, title: "The LORD Comes Down to See", text: "The LORD comes down to look at the city and the tower the people are building.", ref: "Genesis 11:5" },
      { step: 4, title: "Languages Confused", text: "The LORD sees their pride and gives them different languages so they cannot understand one another.", ref: "Genesis 11:7" },
      { step: 5, title: "Scattered Over the Earth", text: "The people stop building the tower, and the LORD scatters them over the face of all the earth.", ref: "Genesis 11:8–9" },
    ],
  },
  {
    id: 5,
    volId: 1,
    title: "The Call of Abraham",
    subtitle: "Leaving home by faith and counting the stars",
    scripture: "Genesis 12 & 15",
    icon: "⛺",
    color: "#e88b6a",
    character: "abraham",
    art: "starry_sky",
    events: [
      { step: 1, title: "A Call to Journey", text: "God calls Abraham: 'Go from your country to the land that I will show you, and I will bless you.'", ref: "Genesis 12:1–3" },
      { step: 2, title: "Pitching Tents by Faith", text: "Abraham, Sarah, and Lot pack their tents and journey into the land of Canaan.", ref: "Genesis 12:4–7" },
      { step: 3, title: "God's Covenant Shield", text: "God promises: 'Fear not, Abraham, I am your shield; your reward shall be very great.'", ref: "Genesis 15:1" },
      { step: 4, title: "Counting the Stars", text: "The LORD brings Abraham outside and says, 'Look toward heaven and count the stars — so shall your offspring be!'", ref: "Genesis 15:5" },
      { step: 5, title: "Believing God's Word", text: "Abraham believes the LORD's promise, and God counts his faith as righteousness.", ref: "Genesis 15:6" },
    ],
  },
  {
    id: 6,
    volId: 1,
    title: "Jacob's Ladder at Bethel",
    subtitle: "A stone pillow, angels ascending, and a sacred vow",
    scripture: "Genesis 28:10–22",
    icon: "🪜",
    color: "#8a6bbf",
    character: "jacob",
    art: "hope_heaven",
    events: [
      { step: 1, title: "Sleeping on a Stone", text: "Jacob journeys toward Haran, sets a stone under his head for a pillow, and falls asleep.", ref: "Genesis 28:10–11" },
      { step: 2, title: "The Stairway to Heaven", text: "In a dream, Jacob sees a stairway reaching from earth to heaven with angels ascending and descending.", ref: "Genesis 28:12" },
      { step: 3, title: "God's Loving Promise", text: "The LORD stands above it and says, 'I am with you and will keep you wherever you go.'", ref: "Genesis 28:13–15" },
      { step: 4, title: "The House of God", text: "Jacob wakes up and says, 'Surely the LORD is in this place! This is none other than the house of God!'", ref: "Genesis 28:16–17" },
      { step: 5, title: "Anointing the Pillar", text: "Jacob sets up the stone as a pillar, pours oil on top of it, and names the place Bethel.", ref: "Genesis 28:18–19" },
    ],
  },

  // --- VOLUME 2: DELIVERANCE & PROMISED LAND ---
  {
    id: 7,
    volId: 2,
    title: "Joseph: From Pit to Palace",
    subtitle: "A coat of colors, dreams, and forgiving his brothers",
    scripture: "Genesis 37–45",
    icon: "🧥",
    color: "#3a86ff",
    character: "joseph",
    art: "love_heart",
    events: [
      { step: 1, title: "The Colorful Coat", text: "Jacob gives his son Joseph a special coat of many bright colors, making his brothers jealous.", ref: "Genesis 37:3–4" },
      { step: 2, title: "Thrown into a Pit", text: "His brothers throw Joseph into a dry cistern and sell him to traveling merchants going to Egypt.", ref: "Genesis 37:23–28" },
      { step: 3, title: "Interpreting Pharaoh's Dreams", text: "God gives Joseph wisdom in Egypt to interpret Pharaoh's dreams about seven years of harvest and famine.", ref: "Genesis 41:25–36" },
      { step: 4, title: "Governor of the Grain", text: "Pharaoh puts Joseph in charge of all Egypt to store up grain for the hungry nations.", ref: "Genesis 41:41–49" },
      { step: 5, title: "Forgiving His Brothers", text: "When his brothers come for food, Joseph weeps for joy and forgives them, saying, 'God sent me ahead of you to save lives.'", ref: "Genesis 45:1–8" },
    ],
  },
  {
    id: 8,
    volId: 2,
    title: "Baby Moses in the Nile Basket",
    subtitle: "A mother's basket, river reeds, and Pharaoh's daughter",
    scripture: "Exodus 2:1–10",
    icon: "🧺",
    color: "#588157",
    character: "miriam",
    art: "calm_waters",
    events: [
      { step: 1, title: "A Mother's Clever Basket", text: "Moses' mother weaves a tar-coated papyrus basket to protect her baby boy from danger.", ref: "Exodus 2:1–3" },
      { step: 2, title: "Placed in the River Reeds", text: "She gently places the basket among the tall reeds along the bank of the Nile River.", ref: "Exodus 2:3" },
      { step: 3, title: "Miriam Watches from Afar", text: "His brave sister Miriam stands watch nearby to see what will happen to the baby.", ref: "Exodus 2:4" },
      { step: 4, title: "Pharaoh's Daughter Finds Him", text: "The princess comes to bathe, hears the crying baby in the basket, and has compassion on him.", ref: "Exodus 2:5–6" },
      { step: 5, title: "Raised in the Palace", text: "Moses' own mother nurses him, and he grows up safe in the palace as the princess's son.", ref: "Exodus 2:7–10" },
    ],
  },
  {
    id: 9,
    volId: 2,
    title: "The Burning Bush",
    subtitle: "Holy ground, blazing fire, and God's call to Moses",
    scripture: "Exodus 3:1–15",
    icon: "🔥",
    color: "#d94f30",
    character: "moses",
    art: "lamp",
    events: [
      { step: 1, title: "Tending Sheep in Midian", text: "Moses leads his father-in-law's flock across the desert to Mount Horeb.", ref: "Exodus 3:1" },
      { step: 2, title: "A Bush Blazing with Fire", text: "Moses sees a bush burning with bright flames, yet the leaves do not burn up!", ref: "Exodus 3:2" },
      { step: 3, title: "Take Off Your Sandals", text: "God calls from the bush: 'Moses! Take off your sandals, for the place where you stand is holy ground.'", ref: "Exodus 3:4–5" },
      { step: 4, title: "I Have Heard My People", text: "The LORD says, 'I have seen the suffering of My people, and I am sending you to lead them out.'", ref: "Exodus 3:7–10" },
      { step: 5, title: "The Name: I AM WHO I AM", text: "God reveals His sacred name: 'Say to the people of Israel: I AM has sent me to you.'", ref: "Exodus 3:14–15" },
    ],
  },
  {
    id: 10,
    volId: 2,
    title: "The Exodus & Red Sea Crossing",
    subtitle: "Pillar of cloud, parted waters, and songs of freedom",
    scripture: "Exodus 14:10–31",
    icon: "🌊",
    color: "#3e7cb1",
    character: "moses",
    art: "calm_waters",
    events: [
      { step: 1, title: "Trapped at the Seashore", text: "The Israelites look back and see Pharaoh's chariots chasing them while the Red Sea blocks their way.", ref: "Exodus 14:10–12" },
      { step: 2, title: "Fear Not, Stand Firm!", text: "Moses tells the people, 'Do not be afraid. Stand firm and see the salvation of the LORD today.'", ref: "Exodus 14:13–14" },
      { step: 3, title: "Stretching the Staff Over Sea", text: "Moses stretches out his hand over the sea, and God drives the waters back with a strong east wind.", ref: "Exodus 14:21" },
      { step: 4, title: "Walking on Dry Ground", text: "The sea parts into two great walls of water, and the Israelites walk safely through on dry ground.", ref: "Exodus 14:22" },
      { step: 5, title: "Singing Praise for Deliverance", text: "The waters close over the chariots, and Moses and Miriam lead Israel in joyful songs and tambourines.", ref: "Exodus 14:30–15:21" },
    ],
  },
  {
    id: 11,
    volId: 2,
    title: "The Ten Commandments at Sinai",
    subtitle: "Thunder on the mountain and stone tablets of the law",
    scripture: "Exodus 19–20; 31:18",
    icon: "📜",
    color: "#b08d57",
    character: "moses",
    art: "wisdom_scroll",
    events: [
      { step: 1, title: "Camp at the Mountain Foot", text: "The people of Israel camp at the base of Mount Sinai, washing their clothes and preparing their hearts.", ref: "Exodus 19:1–11" },
      { step: 2, title: "Thunder, Smoke & Trumpet", text: "A thick cloud covers Mount Sinai with thunder, lightning, and a loud trumpet sound as God descends.", ref: "Exodus 19:16–18" },
      { step: 3, title: "Moses Climbs into the Cloud", text: "Moses walks up the mountain into the cloud to listen to the voice of God.", ref: "Exodus 19:20" },
      { step: 4, title: "The Words of Life", text: "God speaks the Ten Commandments: loving God with all our heart and loving our neighbors.", ref: "Exodus 20:1–17" },
      { step: 5, title: "Written on Stone Tablets", text: "God writes the commandments on two tablets of stone with His own finger and gives them to Moses.", ref: "Exodus 31:18" },
    ],
  },
  {
    id: 12,
    volId: 2,
    title: "The Walls of Jericho",
    subtitle: "Marching in silence, blowing trumpets, and walls falling down",
    scripture: "Joshua 6:1–20",
    icon: "🎺",
    color: "#e63946",
    character: "joshua",
    art: "armor_shield",
    events: [
      { step: 1, title: "A City Tightly Shut", text: "Jericho's high stone walls are locked tight against Israel, but God promises Joshua the victory.", ref: "Joshua 6:1–2" },
      { step: 2, title: "Marching in Silence", text: "For six days, the soldiers and priests carry the Ark and march once around the city in quiet obedience.", ref: "Joshua 6:3–14" },
      { step: 3, title: "Seven Times on the Seventh Day", text: "On the seventh day, they rise at dawn and march around the city walls seven times.", ref: "Joshua 6:15" },
      { step: 4, title: "The Great Shofar Blast", text: "The priests blow their ram's horns, and Joshua commands: 'Shout, for the LORD has given you the city!'", ref: "Joshua 6:16" },
      { step: 5, title: "The Walls Collapse Flat", text: "The people shout with a mighty voice, the huge walls fall down flat, and Israel takes the city.", ref: "Joshua 6:20" },
    ],
  },

  // --- VOLUME 3: JUDGES, KINGS & PROPHETS ---
  {
    id: 13,
    volId: 3,
    title: "Gideon's 300 Brave Men",
    subtitle: "Clay jars, glowing torches, and a midnight victory",
    scripture: "Judges 7:1–22",
    icon: "🏺",
    color: "#b08d57",
    character: "gideon",
    art: "lamp",
    events: [
      { step: 1, title: "A Huge Opposing Army", text: "Gideon gathers an army, but the Midianite camp in the valley is as numerous as sand on the seashore.", ref: "Judges 7:1–3, 12" },
      { step: 2, title: "Testing at the Water", text: "God tells Gideon to choose only the 300 men who lap water from their cupped hands while watching alertly.", ref: "Judges 7:4–7" },
      { step: 3, title: "Equipped with Pitchers & Horns", text: "Each man receives a ram's horn and an empty clay jar with a burning torch hidden inside.", ref: "Judges 7:16" },
      { step: 4, title: "Midnight Torch Blast", text: "At midnight, all 300 men blow their horns, smash their jars, and hold up blazing torches shouting, 'A sword for the LORD and for Gideon!'", ref: "Judges 7:19–20" },
      { step: 5, title: "Victory the LORD Won", text: "The enemy camp panics in the dark and runs away, and God gives Gideon's small band the victory.", ref: "Judges 7:21–22" },
    ],
  },
  {
    id: 14,
    volId: 3,
    title: "Ruth & Naomi's Faithful Harvest",
    subtitle: "Loyal love, golden barley fields, and a family restored",
    scripture: "Ruth 1–4",
    icon: "🌾",
    color: "#f4a261",
    character: "ruth",
    art: "fruit_vine",
    events: [
      { step: 1, title: "Where You Go, I Will Go", text: "Ruth promises her mother-in-law Naomi: 'Where you go I will go, and your God will be my God.'", ref: "Ruth 1:16–17" },
      { step: 2, title: "Gleaning in the Barley Field", text: "Ruth gathers leftover stalks of grain behind the harvesters in the field of kind Boaz.", ref: "Ruth 2:2–3" },
      { step: 3, title: "Boaz Shows Generous Kindness", text: "Boaz tells his workers to drop extra grain on purpose and invites Ruth to eat with his team.", ref: "Ruth 2:8–16" },
      { step: 4, title: "A Guardian Redeemer", text: "Boaz promises to protect and marry Ruth, buying back the family land in Bethlehem.", ref: "Ruth 3:11–4:10" },
      { step: 5, title: "The Great-Grandmother of King David", text: "Ruth and Boaz have a baby named Obed, who becomes the grandfather of King David!", ref: "Ruth 4:13–17" },
    ],
  },
  {
    id: 15,
    volId: 3,
    title: "Young Samuel Hears God's Call",
    subtitle: "A voice in the night and a willing heart: Speak, LORD!",
    scripture: "1 Samuel 3:1–19",
    icon: "🕯️",
    color: "#5c8a3a",
    character: "samuel",
    art: "lamp",
    events: [
      { step: 1, title: "Serving in the Tabernacle", text: "Young Samuel serves the LORD by helping the elderly priest Eli in the tabernacle at Shiloh.", ref: "1 Samuel 3:1" },
      { step: 2, title: "A Voice Calls at Night", text: "While lying down near the Ark, Samuel hears a voice call, 'Samuel! Samuel!' and runs to Eli.", ref: "1 Samuel 3:4–5" },
      { step: 3, title: "Running Three Times", text: "The voice calls three times, and Eli realizes it is the LORD speaking to the boy.", ref: "1 Samuel 3:6–8" },
      { step: 4, title: "Speak, LORD, for Your Servant Hears", text: "Samuel lies down again, and when God calls, he answers: 'Speak, for your servant hears.'", ref: "1 Samuel 3:9–10" },
      { step: 5, title: "A Faithful Prophet of God", text: "Samuel grows up in God's presence, and all Israel learns that the LORD is with him.", ref: "1 Samuel 3:19–20" },
    ],
  },
  {
    id: 16,
    volId: 3,
    title: "David & Goliath in the Valley",
    subtitle: "Five smooth stones, a shepherd's sling, and giant faith",
    scripture: "1 Samuel 17:1–50",
    icon: "🪨",
    color: "#b08d57",
    character: "david",
    art: "armor_shield",
    events: [
      { step: 1, title: "A Giant Taunts the Army", text: "Goliath the giant challenges Israel's soldiers every morning, and everyone trembles in fear.", ref: "1 Samuel 17:4–11" },
      { step: 2, title: "Young David Arrives with Bread", text: "Young shepherd David visits the camp with loaves for his brothers and hears the giant's taunts.", ref: "1 Samuel 17:17–26" },
      { step: 3, title: "Five Smooth Stones from the Brook", text: "David picks five smooth stones from the stream, takes his wooden staff and shepherd's sling.", ref: "1 Samuel 17:40" },
      { step: 4, title: "I Come in the Name of the LORD", text: "David tells Goliath, 'You come with a sword, but I come to you in the name of the LORD of hosts!'", ref: "1 Samuel 17:45" },
      { step: 5, title: "The Stone Strikes True", text: "David swings his sling, the stone strikes the giant's forehead, and God gives Israel the victory.", ref: "1 Samuel 17:49–50" },
    ],
  },
  {
    id: 17,
    volId: 3,
    title: "Solomon Prays for Wisdom",
    subtitle: "A dream in Gibeon and a wise, understanding heart",
    scripture: "1 Kings 3:3–15",
    icon: "👑",
    color: "#3a86ff",
    character: "solomon",
    art: "wisdom_scroll",
    events: [
      { step: 1, title: "A Young King at Gibeon", text: "Young Solomon becomes king over Israel, loves the LORD, and goes to Gibeon to worship Him.", ref: "1 Kings 2:12; 3:3–4" },
      { step: 2, title: "Ask What I Shall Give You", text: "The LORD appears to Solomon in a dream at night and says, 'Ask what I shall give you.'", ref: "1 Kings 3:5" },
      { step: 3, title: "Asking for an Understanding Mind", text: "Solomon does not ask for riches or long life, but asks for wisdom to lead God's people well.", ref: "1 Kings 3:7–9" },
      { step: 4, title: "God Pleased with His Prayer", text: "God says, 'Because you asked for wisdom, I give you a wise mind, plus riches and honor!'", ref: "1 Kings 3:10–14" },
      { step: 5, title: "Wisdom Celebrated in All Nations", text: "Solomon wakes up, gives praise, and people travel from far lands to hear his wisdom.", ref: "1 Kings 3:15, 4:34" },
    ],
  },
  {
    id: 18,
    volId: 3,
    title: "Elijah on Mount Carmel",
    subtitle: "A silent idol, a water-soaked altar, and fire from heaven",
    scripture: "1 Kings 18:20–39",
    icon: "⚡",
    color: "#d94f30",
    character: "elijah",
    art: "light_city",
    events: [
      { step: 1, title: "The Challenge on Mount Carmel", text: "Elijah gathers all the people and false prophets on the mountain to see who the true God is.", ref: "1 Kings 18:20–21" },
      { step: 2, title: "False Prophets Shout in Vain", text: "The false prophets dance and shout all day to their idol, but there is no voice and no answer.", ref: "1 Kings 18:26–29" },
      { step: 3, title: "Twelve Stones & Four Jars of Water", text: "Elijah rebuilds the LORD's altar with twelve stones and pours four big jars of water over it three times.", ref: "1 Kings 18:30–35" },
      { step: 4, title: "A Simple Prayer of Faith", text: "At evening, Elijah prays: 'LORD God of Abraham, let it be known this day that You are God!'", ref: "1 Kings 18:36–37" },
      { step: 5, title: "Fire Falls from Heaven", text: "Fire falls from the sky, consuming the sacrifice, wood, and water, and the people shout, 'The LORD, He is God!'", ref: "1 Kings 18:38–39" },
    ],
  },

  // --- VOLUME 4: FAITH IN EXILE & RETURN ---
  {
    id: 19,
    volId: 4,
    title: "Naaman & The River Jordan",
    subtitle: "A little servant girl's advice and seven river dips",
    scripture: "2 Kings 5:1–14",
    icon: "💧",
    color: "#3e7cb1",
    character: "elisha",
    art: "calm_waters",
    events: [
      { step: 1, title: "A Great General with Sickness", text: "Naaman is a brave army commander, but he suffers from a painful skin disease.", ref: "2 Kings 5:1" },
      { step: 2, title: "A Little Girl's Faithful Clue", text: "A young captive Israelite servant girl tells Naaman's wife about Elisha the prophet who can heal him.", ref: "2 Kings 5:2–3" },
      { step: 3, title: "Go Wash in the Jordan Seven Times", text: "Naaman arrives with horses, and Elisha sends a messenger saying: 'Wash in the Jordan seven times.'", ref: "2 Kings 5:9–10" },
      { step: 4, title: "Humbling His Heart", text: "Naaman's servants encourage him to obey the simple instruction with humility.", ref: "2 Kings 5:13" },
      { step: 5, title: "Clean and Restored Like a Child", text: "Naaman dips in the Jordan River seven times, and his skin is restored fresh and healthy!", ref: "2 Kings 5:14" },
    ],
  },
  {
    id: 20,
    volId: 4,
    title: "Queen Esther's Brave Stand",
    subtitle: "For such a time as this, fasting, and saving her people",
    scripture: "Esther 2–8",
    icon: "👑",
    color: "#8a6bbf",
    character: "esther",
    art: "hope_heaven",
    events: [
      { step: 1, title: "Chosen as Queen of Persia", text: "Humble, kind Esther is chosen to become the queen in the palace of Susa.", ref: "Esther 2:17" },
      { step: 2, title: "A Wicked Plot Revealed", text: "Haman plans a cruel law to destroy all Jewish people throughout the kingdom.", ref: "Esther 3:8–9" },
      { step: 3, title: "For Such a Time as This", text: "Mordecai tells Esther: 'Who knows whether you have not come to the kingdom for such a time as this?'", ref: "Esther 4:14" },
      { step: 4, title: "Praying & Approaching the Throne", text: "Esther fasts for three days, then bravely enters the king's hall, and he holds out his golden scepter to welcome her.", ref: "Esther 4:16–5:2" },
      { step: 5, title: "The People Saved with Joy", text: "The king hears Esther's plea, protects her people, and there is light, gladness, and great joy!", ref: "Esther 7:1–8:17" },
    ],
  },
  {
    id: 21,
    volId: 4,
    title: "Daniel in the Lions' Den",
    subtitle: "Praying three times a day, closed jaws, and morning praise",
    scripture: "Daniel 6:1–23",
    icon: "🦁",
    color: "#b08d57",
    character: "daniel",
    art: "armor_shield",
    events: [
      { step: 1, title: "Faithful in Babylon", text: "Daniel serves King Darius with wisdom and an excellent spirit that pleases the king.", ref: "Daniel 6:1–3" },
      { step: 2, title: "Praying Toward Jerusalem", text: "Even when an unfair law forbids prayer, Daniel opens his window and prays to God three times a day.", ref: "Daniel 6:10" },
      { step: 3, title: "Lowered into the Den", text: "Jealous leaders report Daniel, and the king is forced to put Daniel into a den of hungry lions.", ref: "Daniel 6:16" },
      { step: 4, title: "God Sends an Angel", text: "God sends an angel who shuts the mouths of the lions so they do not harm Daniel at all.", ref: "Daniel 6:22" },
      { step: 5, title: "Lifted Out Unhurt", text: "At dawn, the king rushes to the den and finds Daniel safe because he trusted in his God!", ref: "Daniel 6:23" },
    ],
  },
  {
    id: 22,
    volId: 4,
    title: "The Fiery Furnace",
    subtitle: "Three brave friends, a golden idol, and a fourth in the fire",
    scripture: "Daniel 3:1–28",
    icon: "🔥",
    color: "#d94f30",
    character: "abednego",
    art: "lamp",
    events: [
      { step: 1, title: "The Golden Statue", text: "King Nebuchadnezzar builds a giant gold statue and commands everyone to bow down when music plays.", ref: "Daniel 3:1–5" },
      { step: 2, title: "Refusing to Bow", text: "Shadrach, Meshach, and Abednego refuse to worship any god except the one true LORD.", ref: "Daniel 3:12" },
      { step: 3, title: "Our God Is Able to Deliver Us", text: "They tell the angry king: 'Our God is able to deliver us, but even if He does not, we will not bow!'", ref: "Daniel 3:16–18" },
      { step: 4, title: "A Fourth Person in the Flames", text: "Thrown into the furnace, the king looks in and gasps: 'I see four men walking unhurt in the fire, and the fourth looks like an angel!'", ref: "Daniel 3:24–25" },
      { step: 5, title: "Stepping Out Without Even the Smell of Smoke", text: "The three friends step out safe, not a hair singed, and the king praises the God of heaven.", ref: "Daniel 3:26–28" },
    ],
  },
  {
    id: 23,
    volId: 4,
    title: "Jonah & The Great Fish at Nineveh",
    subtitle: "Running away, storm on the sea, three days in the fish, and repentance",
    scripture: "Jonah 1–3",
    icon: "🐋",
    color: "#3e7cb1",
    character: "jonah",
    art: "calm_waters",
    events: [
      { step: 1, title: "Running to Tarshish", text: "God tells Jonah to preach to Nineveh, but Jonah boards a ship sailing in the opposite direction.", ref: "Jonah 1:1–3" },
      { step: 2, title: "A Great Storm on the Sea", text: "A mighty tempest rocks the ship, and the sailors cast lots and discover Jonah is running from God.", ref: "Jonah 1:4–12" },
      { step: 3, title: "Swallowed by a Great Fish", text: "Jonah is tossed into the sea, the storm calms, and a giant fish swallows Jonah for three days.", ref: "Jonah 1:15–17" },
      { step: 4, title: "Prayer from the Deep", text: "Inside the fish, Jonah prays with thanksgiving: 'Salvation belongs to the LORD!' and the fish spits him on land.", ref: "Jonah 2:1–10" },
      { step: 5, title: "Nineveh Turns to God", text: "Jonah preaches God's warning in Nineveh, the whole city turns to God, and the LORD shows mercy.", ref: "Jonah 3:1–10" },
    ],
  },
  {
    id: 24,
    volId: 4,
    title: "Nehemiah Rebuilds the Walls",
    subtitle: "A weeping cupbearer, stones in 52 days, and songs of joy",
    scripture: "Nehemiah 1–8, 12",
    icon: "🧱",
    color: "#588157",
    character: "nehemiah",
    art: "armor_shield",
    events: [
      { step: 1, title: "Tears for Broken Walls", text: "Nehemiah hears that Jerusalem's stone walls are broken down and burns with prayer and fasting.", ref: "Nehemiah 1:3–4" },
      { step: 2, title: "Sent by the Persian King", text: "The king notices Nehemiah's sad face and graciously sends him to Jerusalem with timber supplies.", ref: "Nehemiah 2:1–8" },
      { step: 3, title: "Working with Trowel and Tool", text: "Families work together side by side, holding building tools in one hand and defenses in the other.", ref: "Nehemiah 4:16–18" },
      { step: 4, title: "Finished in 52 Days", text: "Despite threats from neighbors, the strong city walls are completely rebuilt in just 52 days!", ref: "Nehemiah 6:15–16" },
      { step: 5, title: "The Joy of the LORD Is Your Strength", text: "The people celebrate upon the walls with two big choirs, and their joy is heard far away.", ref: "Nehemiah 8:10, 12:43" },
    ],
  },

  // --- VOLUME 5: THE LIFE & TEACHINGS OF JESUS ---
  {
    id: 25,
    volId: 5,
    title: "The First Christmas in Bethlehem",
    subtitle: "A bright star, hillside shepherds, and angelic good tidings",
    scripture: "Luke 2:1–20, Matthew 2:1–12",
    icon: "⭐",
    color: "#e88b6a",
    character: "luke",
    art: "hope_heaven",
    events: [
      { step: 1, title: "Journey to Bethlehem", text: "Mary and Joseph travel to Bethlehem, where a baby is wrapped in swaddling clothes in a humble manger.", ref: "Luke 2:4–7" },
      { step: 2, title: "Angels Sing to Shepherds", text: "An angel appears to shepherds in night fields, singing: 'Glory to God in the highest, and peace on earth!'", ref: "Luke 2:8–14" },
      { step: 3, title: "Shepherds Hurry to the Manger", text: "The shepherds rush to Bethlehem, find the newborn child in the manger, and tell everyone the good news.", ref: "Luke 2:15–18" },
      { step: 4, title: "Wise Men Reach Jerusalem", text: "Wise men who saw His star in the East arrive in Jerusalem, asking where the newborn King is.", ref: "Matthew 2:1–2" },
      { step: 5, title: "Treasures of Gold and Myrrh", text: "The wise men bow in worship and open treasures of gold, frankincense, and sweet myrrh.", ref: "Matthew 2:11" },
    ],
  },
  {
    id: 26,
    volId: 5,
    title: "Baptism in the Jordan River",
    subtitle: "John in the wilderness, parted skies, and the gentle dove",
    scripture: "Matthew 3:1–17, Mark 1:4–11",
    icon: "🕊️",
    color: "#3e7cb1",
    character: "john_baptist",
    art: "dove_peace",
    events: [
      { step: 1, title: "A Voice in the Wilderness", text: "John the Baptist preaches by the Jordan River, calling all people to prepare their hearts.", ref: "Matthew 3:1–3" },
      { step: 2, title: "Crowds Gather at the Water", text: "Many people come out to be baptized in the flowing waters of the Jordan.", ref: "Matthew 3:5–6" },
      { step: 3, title: "Wading into the Jordan", text: "Jesus comes to the river to fulfill all righteousness, and John baptizes Him in the clear water.", ref: "Matthew 3:13–15" },
      { step: 4, title: "The Spirit Descends Like a Dove", text: "As Jesus comes up from the water, the heavens open and the Spirit descends gently like a dove.", ref: "Matthew 3:16" },
      { step: 5, title: "A Voice from Heaven", text: "A voice from heaven proclaims: 'This is My beloved Son, with whom I am well pleased!'", ref: "Matthew 3:17" },
    ],
  },
  {
    id: 27,
    volId: 5,
    title: "Calming the Storm on Galilee",
    subtitle: "Raging waves, a sleeping teacher, and: Peace, be still!",
    scripture: "Mark 4:35–41",
    icon: "⛵",
    color: "#3a86ff",
    character: "peter",
    art: "calm_waters",
    events: [
      { step: 1, title: "Sailing Across at Evening", text: "The disciples steer their wooden fishing boat across the Sea of Galilee as evening falls.", ref: "Mark 4:35–36" },
      { step: 2, title: "A Furious Windstorm", text: "A sudden violent windstorm kicks up gigantic waves that crash into the boat, filling it with water.", ref: "Mark 4:37" },
      { step: 3, title: "Teacher, Do You Not Care?", text: "The disciples wake Jesus in the stern of the boat, crying: 'Teacher, do You not care that we are sinking?'", ref: "Mark 4:38" },
      { step: 4, title: "Peace, Be Still!", text: "Jesus rises, rebukes the wind, and says to the roaring sea: 'Peace! Be still!'", ref: "Mark 4:39" },
      { step: 5, title: "A Great Calm on the Water", text: "The wind ceases instantly into total glassy calm, and the disciples marvel at His authority.", ref: "Mark 4:39–41" },
    ],
  },
  {
    id: 28,
    volId: 5,
    title: "Feeding the Five Thousand",
    subtitle: "A young boy's lunch, five loaves, two fish, and 12 baskets",
    scripture: "John 6:1–14",
    icon: "🍞",
    color: "#f4a261",
    character: "john",
    art: "fruit_vine",
    events: [
      { step: 1, title: "A Hungry Crowd on the Hill", text: "A vast crowd of over five thousand people gathers on the grassy hillside to listen to teaching.", ref: "John 6:1–5" },
      { step: 2, title: "A Boy's Five Loaves & Two Fish", text: "Andrew says, 'Here is a boy with five barley loaves and two small fish, but what are they among so many?'", ref: "John 6:8–9" },
      { step: 3, title: "Sitting on the Green Grass", text: "Everyone sits down comfortably on the soft green grass by the lakeshore.", ref: "John 6:10" },
      { step: 4, title: "Thanksgiving & Distribution", text: "Jesus gives thanks, breaks the bread, and the disciples pass out as much food as everyone wants.", ref: "John 6:11" },
      { step: 5, title: "Twelve Baskets Left Over", text: "After everyone eats and is satisfied, they collect twelve full baskets of leftover bread pieces!", ref: "John 6:12–13" },
    ],
  },
  {
    id: 29,
    volId: 5,
    title: "The Good Samaritan",
    subtitle: "A traveler in need, oil and bandages, and true neighbor love",
    scripture: "Luke 10:25–37",
    icon: "🩹",
    color: "#d94f30",
    character: "luke",
    art: "love_heart",
    events: [
      { step: 1, title: "A Wounded Traveler", text: "A man travelling down from Jerusalem to Jericho is attacked by robbers and left hurting by the roadside.", ref: "Luke 10:30" },
      { step: 2, title: "Passed by on the Other Side", text: "A priest and a Levite walk down the road, see the injured man, but pass by on the other side.", ref: "Luke 10:31–32" },
      { step: 3, title: "A Samaritan Has Compassion", text: "A Samaritan traveler comes along, sees the hurting man, and his heart fills with deep compassion.", ref: "Luke 10:33" },
      { step: 4, title: "Bandaging Wounds with Oil", text: "He gently dresses the man's wounds with oil and wine, puts him on his donkey, and takes him to an inn.", ref: "Luke 10:34" },
      { step: 5, title: "Go and Do Likewise", text: "He leaves silver coins with the innkeeper to care for the traveler, showing what it means to be a true neighbor.", ref: "Luke 10:35–37" },
    ],
  },
  {
    id: 30,
    volId: 5,
    title: "The Prodigal Son Returns Home",
    subtitle: "A far country, an empty pocket, a running father, and a feast",
    scripture: "Luke 15:11–32",
    icon: "🏡",
    color: "#5c8a3a",
    character: "luke",
    art: "love_heart",
    events: [
      { step: 1, title: "Leaving for a Far Country", text: "A younger son takes his inheritance and travels to a distant land, wasting all his money.", ref: "Luke 15:11–13" },
      { step: 2, title: "Feeding Pigs in the Famine", text: "When famine strikes, he ends up feeding pigs and longs even for the pods the pigs eat.", ref: "Luke 15:14–16" },
      { step: 3, title: "Coming to His Senses", text: "He remembers his father's kindness and says, 'I will arise and go to my father and ask for forgiveness.'", ref: "Luke 15:17–19" },
      { step: 4, title: "A Father Running with Joy", text: "While he is still far off, his father sees him, runs to him, embraces him, and kisses him.", ref: "Luke 15:20" },
      { step: 5, title: "The Best Robe & A Joyful Feast", text: "The father dresses him in the best robe, puts a ring on his hand, and throws a joyful welcome feast!", ref: "Luke 15:22–24" },
    ],
  },

  // --- VOLUME 6: RESURRECTION & THE EARLY CHURCH ---
  {
    id: 31,
    volId: 6,
    title: "The Triumphal Palm Entry",
    subtitle: "A gentle donkey, waving palm branches, and joyful shouts",
    scripture: "Matthew 21:1–11, Mark 11:1–10",
    icon: "🌿",
    color: "#2a9d8f",
    character: "matthew",
    art: "praise_harp",
    events: [
      { step: 1, title: "Finding the Colt", text: "Two disciples find a gentle donkey colt tied in the village, just as they were told.", ref: "Matthew 21:1–3" },
      { step: 2, title: "Spreading Cloaks on the Road", text: "The disciples lay their cloaks on the donkey, and crowds spread their coats across the road.", ref: "Matthew 21:7–8" },
      { step: 3, title: "Waving Green Palm Branches", text: "The crowds cut green palm branches from the trees and wave them high in the air.", ref: "John 12:13" },
      { step: 4, title: "Shouting: Hosanna in the Highest!", text: "The whole crowd sings joyfully: 'Hosanna! Blessed is He who comes in the name of the LORD!'", ref: "Matthew 21:9" },
      { step: 5, title: "The City Stirred with Joy", text: "As the joyful procession enters Jerusalem, the entire city is filled with celebration and wonder.", ref: "Matthew 21:10–11" },
    ],
  },
  {
    id: 32,
    volId: 6,
    title: "Resurrection & The Empty Tomb",
    subtitle: "Dawn light, a rolled-away stone, angels, and: He is risen!",
    scripture: "Luke 24:1–12",
    icon: "🌅",
    color: "#e63946",
    character: "john",
    art: "hope_heaven",
    events: [
      { step: 1, title: "Visiting the Garden at Dawn", text: "Early on Sunday morning at sunrise, faithful women bring sweet spices to the garden tomb.", ref: "Luke 24:1" },
      { step: 2, title: "The Giant Stone Rolled Away", text: "They look up and see that the massive stone in front of the tomb has already been rolled away!", ref: "Luke 24:2" },
      { step: 3, title: "Stepping Inside the Tomb", text: "The women step inside the tomb and find that the body is not there.", ref: "Luke 24:3" },
      { step: 4, title: "He Is Not Here, He Is Risen!", text: "Two angels in gleaming white appear and announce: 'He is not here; He has risen, just as He said!'", ref: "Luke 24:4–6" },
      { step: 5, title: "Running with Overflowing Joy", text: "The women run to tell Peter and the disciples, and the world is filled with everlasting hope.", ref: "Luke 24:8–12" },
    ],
  },
  {
    id: 33,
    volId: 6,
    title: "The Great Commission & Ascension",
    subtitle: "A mountain in Galilee, disciples sent out, and a cloud of promise",
    scripture: "Matthew 28:16–20, Acts 1:6–11",
    icon: "☁️",
    color: "#3a86ff",
    character: "matthew",
    art: "gospel_world",
    events: [
      { step: 1, title: "Meeting on the Mountain", text: "The disciples gather on the mountain in Galilee to meet with their risen Lord.", ref: "Matthew 28:16" },
      { step: 2, title: "All Authority in Heaven and Earth", text: "Jesus speaks words of peace: 'All authority in heaven and on earth has been given to Me.'", ref: "Matthew 28:18" },
      { step: 3, title: "Go and Make Disciples of All Nations", text: "'Go therefore and make disciples of all nations, baptizing them and teaching them to obey.'", ref: "Matthew 28:19–20" },
      { step: 4, title: "I Am with You Always", text: "He gives a comforting promise: 'And behold, I am with you always, to the end of the age.'", ref: "Matthew 28:20" },
      { step: 5, title: "Ascending into the Clouds", text: "Later, near Jerusalem, His disciples watch Him lifted up into a bright cloud, and angels promise He will return one day in glory.", ref: "Acts 1:9–11" },
    ],
  },
  {
    id: 34,
    volId: 6,
    title: "Pentecost & The Rush of Wind",
    subtitle: "Praying in the upper room, sound of mighty wind, and tongues of flame",
    scripture: "Acts 2:1–21",
    icon: "💨",
    color: "#d94f30",
    character: "peter",
    art: "light_city",
    events: [
      { step: 1, title: "Praying in the Upper Room", text: "One hundred and twenty disciples gather together in one place, praying with one accord.", ref: "Acts 1:14–2:1" },
      { step: 2, title: "A Sound Like a Mighty Rushing Wind", text: "Suddenly a sound like a violent blowing wind fills the entire house where they are sitting.", ref: "Acts 2:2" },
      { step: 3, title: "Flames of Fire on Each Head", text: "Tongues that look like flames of fire appear and rest on each of the disciples.", ref: "Acts 2:3" },
      { step: 4, title: "Speaking in Many Languages", text: "Filled with the Holy Spirit, they begin praising God in languages from all over the known world.", ref: "Acts 2:4–11" },
      { step: 5, title: "Peter Preaches with Boldness", text: "Peter stands with the eleven and proclaims God's promises, and three thousand people believe!", ref: "Acts 2:14–41" },
    ],
  },
  {
    id: 35,
    volId: 6,
    title: "Peter & John at the Beautiful Gate",
    subtitle: "No silver or gold, rising to walk, and leaping for joy",
    scripture: "Acts 3:1–16",
    icon: "🏛️",
    color: "#b08d57",
    character: "peter",
    art: "praise_harp",
    events: [
      { step: 1, title: "Walking to the Temple to Pray", text: "Peter and John walk up to the temple at the hour of prayer in the afternoon.", ref: "Acts 3:1" },
      { step: 2, title: "A Man Begging at the Gate", text: "A man who had never walked since birth sits at the gate called Beautiful, asking for coins.", ref: "Acts 3:2–3" },
      { step: 3, title: "Look at Us!", text: "Peter looks straight at him and says, 'Silver and gold I do not have, but what I have I give you.'", ref: "Acts 3:4–6a" },
      { step: 4, title: "In the Name of Jesus, Rise and Walk!", text: "Peter takes him by the right hand, pulls him up, and instantly his feet and ankles are made strong!", ref: "Acts 3:6b–7" },
      { step: 5, title: "Walking, Leaping & Praising God", text: "The man jumps to his feet, walking and leaping into the temple courts, praising God with all his heart.", ref: "Acts 3:8–9" },
    ],
  },
  {
    id: 36,
    volId: 6,
    title: "Paul on the Damascus Road",
    subtitle: "A blinding light, a voice from heaven, and a changed heart",
    scripture: "Acts 9:1–22",
    icon: "☀️",
    color: "#8a6bbf",
    character: "paul",
    art: "gospel_world",
    events: [
      { step: 1, title: "Journeying to Damascus", text: "Saul breathes threats against the believers and travels to Damascus with letters of arrest.", ref: "Acts 9:1–2" },
      { step: 2, title: "A Light Brighter Than the Sun", text: "Suddenly a blazing light from heaven flashes all around him, and he falls to the ground.", ref: "Acts 9:3–4" },
      { step: 3, title: "Why Do You Persecute Me?", text: "He hears a voice say: 'Saul, Saul, why do you persecute Me?' and asks: 'Who are You, Lord?'", ref: "Acts 9:4–5" },
      { step: 4, title: "Ananias Prays in Faith", text: "Led by the hand to Damascus, Ananias visits Saul, lays hands on him, and his eyesight returns.", ref: "Acts 9:8–18" },
      { step: 5, title: "Proclaiming the Good News", text: "Saul is baptized and immediately begins proclaiming in the synagogues that Jesus is the Son of God!", ref: "Acts 9:18–20" },
    ],
  },
];

// Pure scoring helper: Generous scoring for children
export function starsForAttempts(attempts) {
  if (attempts <= 2) return 3;
  if (attempts <= 4) return 2;
  return 1;
}

// Get all stories belonging to a volume
export function getVolumeStories(volId) {
  return STORIES.filter((s) => s.volId === volId);
}

// Get a story by its 1-indexed id
export function getStoryById(id) {
  return STORIES.find((s) => s.id === id) || STORIES[0];
}

export function shuffleEvents(story, seed = 0) {
  const original = story.events.map((ev, idx) => ({ ...ev, currentIdx: idx }));
  let shuffled = shuffle(original, story.id * 107 + seed * 19 + 7);
  // Guarantee the starting order is not already solved
  const isAlreadySolved = shuffled.every((ev, i) => ev.step === i + 1);
  if (isAlreadySolved) {
    shuffled = [shuffled[1], shuffled[0], ...shuffled.slice(2)];
  }
  return shuffled;
}

// Check which event cards are currently in their correct chronological step
export function evaluateOrder(events) {
  const results = events.map((ev, i) => ev.step === i + 1);
  const correctCount = results.filter(Boolean).length;
  const isComplete = correctCount === events.length;
  return { results, correctCount, isComplete, total: events.length };
}
